---
- hosts: localhost
  vars:
    message: "Hello, Welcome to Ansible World!"
  remote_user: root

  tasks:
   #Copy Hello message to temp dir
    - copy:
       content: "{{message}}"
       dest: /tmp/hello.txt
       mode: 0555
